speedtest:
  servers:
    - 15047 # speed.open.ad.jp
    - 14623 # speed.coe.ad.jp
  threads: 1

ambient:
  dataLink:
    32907: # speedtest.unko.co.jp
      download:
        channelId: <channelId>
        writeKey: <writeKey>
      upload:
        channelId: <channelId>
        writeKey: <writeKey>
    14623: # speed.coe.ad.jp
      download:
        channelId: <channelId>
        writeKey: <writeKey>
      upload:
        channelId: <channelId>
        writeKey: <writeKey>
